/* Run against a built portal: NODE_PATH=<playwright install>/node_modules
 * EAOPS_CHROMIUM=<optional executable> node tests/browser_smoke.cjs docs/index.html
 * Playwright is a test-only dependency, never shipped in the portal. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const http = require('node:http');
const { chromium } = require('playwright');
(async () => {
  const html = fs.readFileSync(process.argv[2] || 'docs/index.html');
  const server = http.createServer((req, res) => { res.setHeader('Content-Type', 'text/html; charset=utf-8'); res.end(html); });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  let browser;
  try {
    browser = await chromium.launch({headless: true, executablePath: process.env.EAOPS_CHROMIUM || undefined, args: ['--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--no-zygote']});
    const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    const base = `http://127.0.0.1:${server.address().port}/`;
    await page.goto(base);
    await page.locator('[data-page="catalog"]').click();
    const total = await page.locator('#catalogResults tbody tr').count();
    assert(total > 0);
    await page.locator('#catalogSearch').fill('THIS DOES NOT EXIST 92834');
    assert.equal(await page.locator('#catalogResults tbody tr').count(), 0);
    assert.match(await page.locator('#catalogResults').innerText(), /No matching objects/);
    await page.locator('#resetCatalog').click();
    assert.equal(await page.locator('#catalogResults tbody tr').count(), total);
    const first = page.locator('#catalogResults [data-open-object]').first();
    const id = await first.getAttribute('data-open-object');
    await page.locator('#catalogResults [data-favorite]').first().click();
    await page.locator('#catalogScope').selectOption('favorites');
    assert.equal(await page.locator('#catalogResults tbody tr').count(), 1);
    const downloadPromise = page.waitForEvent('download');
    await page.locator('#exportCatalog').click();
    const download = await downloadPromise;
    const csv = fs.readFileSync(await download.path(), 'utf8');
    assert(csv.includes(id));
    assert.match(csv, /"ID","Name"/);
    assert.equal(await page.evaluate(() => csvCell('=1+1')), '"\'=1+1"');
    await page.locator('#catalogResults [data-open-object]').first().click();
    assert.equal(new URL(page.url()).hash, '#object='+encodeURIComponent(id));
    await page.reload();
    assert.equal(new URL(page.url()).hash, '#object='+encodeURIComponent(id));
    await page.locator('[data-page="overview"]').click();
    assert(await page.locator('#dailyWorkspace [data-open-object]').count() >= 2);
    await page.locator('[data-page="catalog"]').click();
    await page.locator('#catalogScope').selectOption('favorites');
    assert.equal(await page.locator('#catalogResults tbody tr').count(), 1);
    await page.goto(base+'#object=deleted-object');
    assert(await page.locator('#page-catalog').evaluate(el => el.classList.contains('active')));
    await page.keyboard.press('/');
    assert.equal(await page.evaluate(() => document.activeElement.id), 'globalSearch');
    await page.locator('#globalSearch').fill(id);
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('#catalogResults tbody tr').count(), 1);
    await page.locator('#resetCatalog').click();
    await page.locator('#catalogLayer').selectOption('application');
    assert((await page.locator('#catalogResults tbody tr').count()) > 0);
    assert((await page.locator('#catalogResults tbody tr').count()) < total);
    await page.locator('[data-page="overview"]').click();
    if (process.env.EAOPS_SCREENSHOTS) await page.screenshot({path: process.env.EAOPS_SCREENSHOTS+'/desktop.png', fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    if (process.env.EAOPS_SCREENSHOTS) await page.screenshot({path: process.env.EAOPS_SCREENSHOTS+'/mobile.png', fullPage:true});
    await page.locator('[data-page="catalog"]').click();
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.close();
    const blocked = await browser.newPage();
    blocked.on('pageerror', e => errors.push(e.message));
    await blocked.addInitScript(() => { Object.defineProperty(window, 'localStorage', {get(){throw new Error('Storage blocked');}}); });
    await blocked.goto(base);
    await blocked.locator('[data-page="catalog"]').click();
    await blocked.locator('#catalogResults [data-favorite]').first().click();
    await blocked.locator('#catalogScope').selectOption('favorites');
    assert.equal(await blocked.locator('#catalogResults tbody tr').count(),1);
    assert.deepEqual(errors, []);
    console.log(`PASS: ${total} objects; search, filters, favorites, persistence, CSV, links, keyboard, mobile layout, blocked storage; no JavaScript errors.`);
  } finally { if (browser) await browser.close(); server.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
