from __future__ import annotations

from collections import Counter
from html import escape
from pathlib import Path
import json

from .core import RepositoryModel, metrics, validate


def _page_shell(title: str, body: str, data_json: str = "{}") -> str:
    return f"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{escape(title)}</title><style>
:root{{--ink:#0b1220;--muted:#60708a;--line:#dce3ec;--bg:#f6f8fb;--card:#fff;--brand:#4f46e5;--brand2:#0ea5e9;--good:#057a55;--warn:#b45309;--bad:#b42318}}*{{box-sizing:border-box}}body{{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;background:var(--bg);color:var(--ink)}}a{{color:inherit}}.wrap{{max-width:1180px;margin:auto;padding:0 24px}}header{{background:#081225;color:white;border-bottom:1px solid #1d2b44}}nav{{height:68px;display:flex;align-items:center;justify-content:space-between}}.brand{{font-weight:800;font-size:22px;letter-spacing:-.04em}}.brand span{{color:#67e8f9}}.navlinks{{display:flex;gap:22px;font-size:14px;color:#cbd5e1}}.hero{{background:radial-gradient(circle at 75% 5%,#164e63 0,transparent 28%),linear-gradient(145deg,#081225,#101e3b);color:white;padding:72px 0 58px}}.eyebrow{{font-size:12px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;color:#67e8f9}}h1{{font-size:56px;line-height:1.02;letter-spacing:-.055em;margin:13px 0 18px;max-width:820px}}.lead{{font-size:20px;line-height:1.6;color:#cbd5e1;max-width:820px}}.pill{{display:inline-block;padding:8px 12px;border:1px solid #2f4165;border-radius:999px;font-size:13px;color:#dbeafe;margin-right:8px;margin-top:16px}}section{{padding:42px 0}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}}.card{{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:20px;box-shadow:0 8px 28px rgba(17,24,39,.04)}}.metric strong{{display:block;font-size:30px;letter-spacing:-.04em}}.metric small{{color:var(--muted)}}h2{{font-size:30px;letter-spacing:-.035em;margin:0 0 18px}}.muted{{color:var(--muted)}}.toolbar{{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:18px}}input,select{{background:white;border:1px solid var(--line);border-radius:10px;padding:11px 13px;min-width:220px}}table{{width:100%;border-collapse:collapse;background:white;border:1px solid var(--line);border-radius:14px;overflow:hidden}}th,td{{padding:12px 14px;border-bottom:1px solid var(--line);text-align:left;font-size:14px}}th{{background:#f8fafc;color:#475569}}.badge{{padding:4px 8px;border-radius:999px;font-size:12px;background:#eef2ff;color:#3730a3}}.ok{{color:var(--good)}}.warning{{color:var(--warn)}}.error{{color:var(--bad)}}.flow{{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}}.flow .card{{min-height:128px}}.flow b{{display:block;margin-bottom:6px}}.flow small{{color:var(--muted);line-height:1.45}}footer{{border-top:1px solid var(--line);padding:26px 0;color:var(--muted);font-size:13px}}@media(max-width:850px){{h1{{font-size:42px}}.grid,.flow{{grid-template-columns:1fr 1fr}}}}@media(max-width:540px){{.grid,.flow{{grid-template-columns:1fr}}.navlinks{{display:none}}}}
</style></head><body><header><div class='wrap'><nav><div class='brand'>EA<span>-Ops</span></div><div class='navlinks'><a href='#catalog'>Catalog</a><a href='#quality'>Quality</a><a href='#governance'>Governance</a></div></nav></div></header>{body}<footer><div class='wrap'>EA-Ops · Enterprise Architecture as Code · Apache-2.0</div></footer><script>window.EAOPS={data_json};const q=document.getElementById('q');const t=document.getElementById('type');function f(){{document.querySelectorAll('[data-row]').forEach(r=>{{const text=r.textContent.toLowerCase();const typ=r.dataset.type;const show=(!q||!q.value||text.includes(q.value.toLowerCase()))&&(!t||!t.value||typ===t.value);r.style.display=show?'':'none'}})}}if(q)q.addEventListener('input',f);if(t)t.addEventListener('change',f);</script></body></html>"""


def render_portal(repo: RepositoryModel, output_dir: str | Path) -> Path:
    output_dir = Path(output_dir); output_dir.mkdir(parents=True, exist_ok=True)
    issues = validate(repo); m = metrics(repo, issues); type_counts = Counter(o.get("type", "Unknown") for o in repo.objects.values()); types = sorted(type_counts)
    rows = []
    for oid, obj in sorted(repo.objects.items(), key=lambda kv: (kv[1].get("type", ""), kv[1].get("name", ""))):
        props = obj.get("properties") or {}
        rows.append(f"<tr data-row data-type='{escape(obj.get('type',''))}'><td><strong>{escape(obj.get('name',''))}</strong><br><span class='muted'>{escape(oid)}</span></td><td><span class='badge'>{escape(obj.get('type',''))}</span></td><td>{escape(str(props.get('owner','—')))}</td><td>{escape(str(props.get('lifecycle','active')))}</td></tr>")
    issue_rows = [f"<tr><td class='{escape(i.severity)}'>{escape(i.severity.upper())}</td><td>{escape(i.code)}</td><td>{escape(i.object_id or '—')}</td><td>{escape(i.message)}</td></tr>" for i in issues]
    if not issue_rows: issue_rows.append("<tr><td class='ok'>PASS</td><td>MODEL_VALID</td><td>—</td><td>No validation findings.</td></tr>")
    flow = [("Model", "Flexible objects and relationships in YAML."),("Validate", "Deterministic metamodel and policy checks."),("Review", "Pull requests expose the architecture change."),("Govern", "Owners and policies determine approval."),("Publish", "Catalogs, reports and views from one source.")]
    body = f"""<div class='hero'><div class='wrap'><div class='eyebrow'>Git-native enterprise architecture operations</div><h1>Architecture becomes a governed, testable product.</h1><div class='lead'>EA-Ops turns enterprise architecture into versioned model data that can be validated in CI, reviewed through pull requests, analyzed for impact and published as an accessible architecture portal.</div><div><span class='pill'>ArchiMate-compatible profile</span><span class='pill'>Policy as code</span><span class='pill'>Pull-request governance</span><span class='pill'>Static portal</span></div></div></div><section><div class='wrap'><div class='grid'><div class='card metric'><small>Architecture objects</small><strong>{m['objects']}</strong><span class='muted'>across {len(types)} types</span></div><div class='card metric'><small>Relationships</small><strong>{m['relationships']}</strong><span class='muted'>resolved graph links</span></div><div class='card metric'><small>Ownership coverage</small><strong>{m['ownershipCoverage']}%</strong><span class='muted'>governance readiness</span></div><div class='card metric'><small>Quality score</small><strong>{m['qualityScore']}</strong><span class='muted'>{m['errors']} errors · {m['warnings']} warnings</span></div></div></div></section><section id='governance'><div class='wrap'><h2>One operating model</h2><div class='flow'>{''.join(f"<div class='card'><b>{n}</b><small>{d}</small></div>" for n,d in flow)}</div></div></section><section id='catalog'><div class='wrap'><h2>Enterprise catalog</h2><div class='toolbar'><input id='q' placeholder='Search architecture…'><select id='type'><option value=''>All types</option>{''.join(f"<option>{escape(x)}</option>" for x in types)}</select></div><table><thead><tr><th>Element</th><th>Type</th><th>Owner</th><th>Lifecycle</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div></section><section id='quality'><div class='wrap'><h2>Architecture quality & policy</h2><p class='muted'>Generated from the same repository model used by CI.</p><table><thead><tr><th>Severity</th><th>Rule</th><th>Object</th><th>Finding</th></tr></thead><tbody>{''.join(issue_rows)}</tbody></table></div></section>"""
    data = json.dumps({"metrics": m, "types": dict(type_counts)}, ensure_ascii=False)
    out = output_dir / "index.html"; out.write_text(_page_shell("EA-Ops · Enterprise Architecture Operations", body, data), encoding="utf-8"); return out


def render_report(repo: RepositoryModel, output_file: str | Path) -> Path:
    output_file = Path(output_file); output_file.parent.mkdir(parents=True, exist_ok=True)
    issues = validate(repo); m = metrics(repo, issues); by_type = Counter(o.get("type", "Unknown") for o in repo.objects.values())
    lines = ["# EA-Ops Architecture Report","","## Executive Summary","",f"- Quality score: **{m['qualityScore']}/100**",f"- Objects: **{m['objects']}**",f"- Relationships: **{m['relationships']}**",f"- Ownership coverage: **{m['ownershipCoverage']}%**",f"- Validation: **{m['errors']} errors**, **{m['warnings']} warnings**","","## Catalog by Type","","| Type | Count |","|---|---:|"]
    lines += [f"| {t} | {n} |" for t,n in sorted(by_type.items())]
    lines += ["","## Validation Findings","","| Severity | Rule | Object | Finding |","|---|---|---|---|"]
    lines += [f"| {i.severity} | {i.code} | {i.object_id or '—'} | {i.message} |" for i in issues] if issues else ["| pass | MODEL_VALID | — | No validation findings |"]
    lines += ["","## Governance Statement","","`main` represents the approved architecture. Proposed changes are reviewed as pull requests and validated before merge."]
    output_file.write_text("\n".join(lines)+"\n", encoding="utf-8"); return output_file
